framework:
  - terraform

external-checks-dir:
  - ./custom_checks

soft-fail: false

quiet: false

skip-check:
  - CKV_AWS_233
  - CKV_AWS_150
  - CKV_AWS_91
  - CKV_AWS_131
  - CKV_AWS_119
  - CKV_AWS_28
  - CKV_AWS_79
  - CKV_AWS_135
  - CKV_AWS_8
  - CKV_AWS_126
  - CKV_AWS_353
  - CKV_AWS_226
  - CKV_AWS_129
  - CKV_AWS_293
  - CKV_AWS_161
  - CKV_AWS_118
  - CKV_AWS_23
  - CKV_AWS_260
  - CKV2_AWS_6 
  - CKV2_AWS_12
  - CKV2_AWS_30
  - CKV_AWS_145
  - CKV2_AWS_11
  - CKV_AWS_378
  - CKV2_AWS_5
  - CKV_AWS_18 
  - CKV2_AWS_60 
  - CKV_AWS_144
  - CKV2_AWS_74
  - CKV_AWS_103
  - CKV2_AWS_28
  - CKV2_AWS_62

# checkov -d terraform --config-file policies/checkov/config.yaml
