version: "3.9"

services:
  fast_api:
    image: silasfrancis/devops-api-dev:ddce371-0000-gddce371    
    container_name: fastapi
    pull_policy: always
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: devdb
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn conduit.app:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8080:8000"                  
    depends_on:
      - postgres                     

  react_app:
    image: silasfrancis/devops-client-dev:ddce371-0000-gddce371
    container_name: react_app
    pull_policy: always
    environment:
      HOST: "0.0.0.0"
      PORT: 3000
      CHOKIDAR_USEPOLLING: true
    ports:
      - "3000:3000"
    depends_on:
      - fast_api
