all:
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_region: us-east-2
    ansible_aws_ssm_bucket_name: ansible-ssm-silas-test
    ansible_aws_ssm_s3_addressing_style: virtual

  children:
    application:
      hosts:
        instance1:
          ansible_host: i-0054034de59167478
    #     instance2:
    #       ansible_host: i-0730e9c8a7c92e4ca

    # wireguard:
    #   hosts:
    #     wg_instance:
    #       ansible_host: i-06ae1a92439c6a567
